// Code generated by ent, DO NOT EDIT.

package order

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldProductLogo holds the string denoting the product_logo field in the database.
	FieldProductLogo = "product_logo"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldDenomination holds the string denoting the denomination field in the database.
	FieldDenomination = "denomination"
	// FieldOriginalPrice holds the string denoting the original_price field in the database.
	FieldOriginalPrice = "original_price"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldNum holds the string denoting the num field in the database.
	FieldNum = "num"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUDeleteTime holds the string denoting the u_delete_time field in the database.
	FieldUDeleteTime = "u_delete_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the order in the database.
	Table = "order_copy_tmp"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldOrderNo,
	FieldUserID,
	FieldProductID,
	FieldProductName,
	FieldProductLogo,
	FieldPrice,
	FieldDenomination,
	FieldOriginalPrice,
	FieldUnitPrice,
	FieldNum,
	FieldProductType,
	FieldStatus,
	FieldUDeleteTime,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
