// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Category struct {
	ent.Schema
}

func (Category) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("title").Comment("分类名称"), field.String("icon").Comment("icon")}
}
func (Category) Edges() []ent.Edge {
	return nil
}
func (Category) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "category"}}
}
