// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoryColumns holds the columns for the "category" table.
	CategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
	}
	// CategoryTable holds the schema information for the "category" table.
	CategoryTable = &schema.Table{
		Name:       "category",
		Columns:    CategoryColumns,
		PrimaryKey: []*schema.Column{CategoryColumns[0]},
	}
	// OrderCopyTmpColumns holds the columns for the "order_copy_tmp" table.
	OrderCopyTmpColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_no", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "product_name", Type: field.TypeString},
		{Name: "product_logo", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "denomination", Type: field.TypeFloat64},
		{Name: "original_price", Type: field.TypeFloat64},
		{Name: "unit_price", Type: field.TypeFloat64},
		{Name: "num", Type: field.TypeInt},
		{Name: "product_type", Type: field.TypeInt},
		{Name: "status", Type: field.TypeInt},
		{Name: "u_delete_time", Type: field.TypeTime, Nullable: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
	}
	// OrderCopyTmpTable holds the schema information for the "order_copy_tmp" table.
	OrderCopyTmpTable = &schema.Table{
		Name:       "order_copy_tmp",
		Columns:    OrderCopyTmpColumns,
		PrimaryKey: []*schema.Column{OrderCopyTmpColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoryTable,
		OrderCopyTmpTable,
	}
)

func init() {
	CategoryTable.Annotation = &entsql.Annotation{
		Table: "category",
	}
	OrderCopyTmpTable.Annotation = &entsql.Annotation{
		Table: "order_copy_tmp",
	}
}
